#!/bin/bash

bin/hw < test/01.test
sleep 0.9
bin/hw < test/02.test
sleep 1.7
bin/hw < test/03.test
sleep 0.8
bin/hw < test/04.test
sleep 2.5
bin/hw < test/10.test
sleep 0.8
bin/hw < test/11.test
sleep 1.9
bin/hw < test/12.test
sleep 0.1
bin/hw < test/01.test
sleep 0.8
bin/hw < test/02.test
sleep 0.9
bin/hw < test/03.test
sleep 2.3
bin/hw < test/04.test
sleep 1.4
bin/hw < test/10.test
sleep 0.8
bin/hw < test/11.test
sleep 0.3
bin/hw < test/12.test

bin/databuilder < tmp/hw.log > tmp/plot.dat
gnuplot monitoring/plot.gnu
